name: Python CI-CD

on: [push, workflow_dispatch]

jobs:

  lint-and-test:
    name: Lint and test python code
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install other dependencies
        run: pip install flake8 pylint
      
      - name: Lint the code
        run: |
          flake8 hello.py
          lint hello.py

      - name: Test the script
        run: python hello.py | grep -i hello || exit 1

  build-and-push:
    name: build python code and docker image
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # Extract metadata(tags, labels) for docker
        #https://github.com/docker/metadata-action
      - name: Extract docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ghcr.io/${{github.repository}}
          tags: |
            type=sha,format=short,prefix=,suffix=
            type=sha,format=long,prefix=,suffix=
            type=ref,format=branch,prefix=,suffix=

        # Build and push Docker image with buildx
        # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}


  execute-image:
    name: Pull docker image and execute it
    needs: [build-and-push]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Login to github container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: $${{secrets.GITHUB_TOKEN}}

      - name: pull image from Github container registry
          run: docker pull ghcr.io/${{github.repository}}:${{github.sha}}

      - name: run image
          run: docker run --rm ghcr.io/${{github.repository}}:${{github.sha}} | grep -i hello || exit 1